version: "3.9"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - mynetwork
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://admin:adminpassword@mongodb:27017
      PORT: 5000
    depends_on:
      - mongodb

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - mynetwork
    environment:
      REACT_APP_API_URL: http://backend:5000/api
    depends_on:
      - backend

networks:
  mynetwork:

volumes:
  mongodb_data:
